### ISSUE TITLE
Wrong link?

### ISSUE THREAD

**Issue by th1j5** [johnperry-math/mew_cats#1]
Page 8: "We prefer Sage for a number of reasons:"

The hyperlink embedded in 'Sage' points to `sagemath.com`, which redirects to `cocalc.com`.
I guess you actually meant `sagemath.org`.

(I'm not sure in which source files you would want any modification - lyx or tex, so I just made an issue)

**Comment by johnperry-math** [comment]
Fix appears in `draft19.lyx`. I typically update the lax file and export to latex.

Thank you! :-)
